### ISSUE TITLE
I would like to add motivational quote on your website

### ISSUE THREAD

**Issue by DEV-Dhruva** [Mark-42-max/Motivations-Collection#20]
hey @Mark-42-max , will you assign this issue to me.

**Comment by theDevSoham** [comment]
Of course go ahead

**Comment by ZunaidAnsari017** [comment]
Hello, @Mark-42-max I am new to open source. Can you assign me to this issue?

**Comment by Mark-42-max** [comment]
@zunaidrahmani sure

**Comment by theDevSoham** [comment]
If you want to contribute please fork the repo and follow the instructions on the repo description. No need to create an issue for this @DEV-Dhruva @zunaidrahmani
