### ISSUE TITLE
Dynamic Rendering Of Quotes

### ISSUE THREAD

**Issue by LogicAddict** [Mark-42-max/Motivations-Collection#69]
Hey, can I add a dynamic function in JS file so that the contributors can only add or edit a JSON or JS object, without editing HTML file.

**Comment by theDevSoham** [comment]
Hi @Muhammad-Anus-Developer , that's the feature needed for this project, but not right now. Currently all contributions are accepted in HTML format. I might open this issue later, however this is not required at the moment

**Comment by LogicAddict** [comment]
Yeah alright I can understand but this feature can add advancement in your motivation collection project you can do it afterwards when you need. 😇

**Comment by theDevSoham** [comment]
Thanks for showing support. 💝

**Comment by LogicAddict** [comment]
No Problem
